2022-04-14T19:49:23,195 Using pip 22.0.4 from C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
2022-04-14T19:49:23,197 Non-user install because site-packages writeable
2022-04-14T19:49:23,231 Created temporary directory: C:\Users\Jonathan\AppData\Local\Temp\pip-ephem-wheel-cache-gme3u23r
2022-04-14T19:49:23,232 Created temporary directory: C:\Users\Jonathan\AppData\Local\Temp\pip-req-tracker-b5fsqosm
2022-04-14T19:49:23,232 Initialized build tracking at C:\Users\Jonathan\AppData\Local\Temp\pip-req-tracker-b5fsqosm
2022-04-14T19:49:23,232 Created build tracker: C:\Users\Jonathan\AppData\Local\Temp\pip-req-tracker-b5fsqosm
2022-04-14T19:49:23,233 Entered build tracker: C:\Users\Jonathan\AppData\Local\Temp\pip-req-tracker-b5fsqosm
2022-04-14T19:49:23,233 Created temporary directory: C:\Users\Jonathan\AppData\Local\Temp\pip-install-5qxyh3bs
2022-04-14T19:49:23,248 1 location(s) to search for versions of requirements-txt:
2022-04-14T19:49:23,248 * https://pypi.org/simple/requirements-txt/
2022-04-14T19:49:23,249 Fetching project page and analyzing links: https://pypi.org/simple/requirements-txt/
2022-04-14T19:49:23,249 Getting page https://pypi.org/simple/requirements-txt/
2022-04-14T19:49:23,250 Found index url https://pypi.org/simple
2022-04-14T19:49:23,561 Could not fetch URL https://pypi.org/simple/requirements-txt/: 404 Client Error: Not Found for url: https://pypi.org/simple/requirements-txt/ - skipping
2022-04-14T19:49:23,561 Skipping link: not a file: https://pypi.org/simple/requirements-txt/
2022-04-14T19:49:23,562 Given no hashes to check 0 links for project 'requirements-txt': discarding no candidates
2022-04-14T19:49:23,563 ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
2022-04-14T19:49:23,565 HINT: You are attempting to install a package literally named "requirements.txt" (which cannot exist). Consider using the '-r' flag to install the packages listed in requirements.txt
2022-04-14T19:49:23,565 ERROR: No matching distribution found for requirements.txt
2022-04-14T19:49:23,566 Exception information:
2022-04-14T19:49:23,566 Traceback (most recent call last):
2022-04-14T19:49:23,566   File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
2022-04-14T19:49:23,566     self._add_to_criteria(self.state.criteria, r, parent=None)
2022-04-14T19:49:23,566   File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
2022-04-14T19:49:23,566     raise RequirementsConflicted(criterion)
2022-04-14T19:49:23,566 pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('requirements.txt')
2022-04-14T19:49:23,566 
2022-04-14T19:49:23,566 During handling of the above exception, another exception occurred:
2022-04-14T19:49:23,566 
2022-04-14T19:49:23,566 Traceback (most recent call last):
2022-04-14T19:49:23,566   File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
2022-04-14T19:49:23,566     result = self._result = resolver.resolve(
2022-04-14T19:49:23,566   File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
2022-04-14T19:49:23,566     state = resolution.resolve(requirements, max_rounds=max_rounds)
2022-04-14T19:49:23,566   File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 350, in resolve
2022-04-14T19:49:23,566     raise ResolutionImpossible(e.criterion.information)
2022-04-14T19:49:23,566 pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('requirements.txt'), parent=None)]
2022-04-14T19:49:23,566 
2022-04-14T19:49:23,566 The above exception was the direct cause of the following exception:
2022-04-14T19:49:23,566 
2022-04-14T19:49:23,566 Traceback (most recent call last):
2022-04-14T19:49:23,566   File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
2022-04-14T19:49:23,566     status = run_func(*args)
2022-04-14T19:49:23,566   File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
2022-04-14T19:49:23,566     return func(self, options, args)
2022-04-14T19:49:23,566   File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\install.py", line 339, in run
2022-04-14T19:49:23,566     requirement_set = resolver.resolve(
2022-04-14T19:49:23,566   File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 103, in resolve
2022-04-14T19:49:23,566     raise error from e
2022-04-14T19:49:23,566 pip._internal.exceptions.DistributionNotFound: No matching distribution found for requirements.txt
2022-04-14T19:49:23,576 Removed build tracker: 'C:\\Users\\Jonathan\\AppData\\Local\\Temp\\pip-req-tracker-b5fsqosm'
